### ISSUE TITLE
Library update needed

### ISSUE THREAD

**Issue by maganap** [frcc00/frccblue#1]
Hello!

I need to transfer a file from one BLE device to another. Both will be flutter apps. There's a lot of flutter libraries out there to act as a BLE client, but I couldn't find any library to act as a peripheral device except yours.  But it is so outdated that it's not usable anymore.

Is there any chance you could work on updating your library? I'm willing to sponsor this project if needed.  Please let me know what you think.

Thanks!

**Comment by frcc00** [comment]
> Hello!
> 
> I need to transfer a file from one BLE device to another. Both will be flutter apps. There's a lot of flutter libraries out there to act as a BLE client, but I couldn't find any library to act as a peripheral device except yours. But it is so outdated that it's not usable anymore.
> 
> Is there any chance you could work on updating your library? I'm willing to sponsor this project if needed. Please let me know what you think.
> 
> Thanks!

i will update tomorrow
