### ISSUE TITLE
startAdvertising cannot be start for more than one time

### ISSUE THREAD

**Issue by rebeccalee-ysd** [frcc00/frccblue#2]
startAdvertising cannot be start for more than one time
My application had call startAdvertising and it is works,(both send and receive characteristic). But after that, after i called stopAdvertising and try to startAdvertising again, it doesn't work any more.(means can't send and receive characteristic) What can I do for this? Thanks a lot.

**Comment by rebeccalee-ysd** [comment]
>when i am able to startAdvertising successfully.
<img width="1155" alt="Screenshot 2020-08-27 at 10 26 45 AM" src="https://user-images.githubusercontent.com/68107203/91412997-1808b000-e87d-11ea-8e6e-d58c0a0e9536.png">

> fail 
<img width="840" alt="Screenshot 2020-08-27 at 10 28 59 AM" src="https://user-images.githubusercontent.com/68107203/91413081-32db2480-e87d-11ea-9e2a-04456472df6a.png">

i mention that the different is:
> success: the log will show: BLE support array set: 010011

**Comment by rebeccalee-ysd** [comment]
private fun stopAdvertising() {
        if (mBluetoothLeAdvertiser == null) return
        if (mGattServer != null) {
            mGattServer!!.close()
        }
        mBluetoothLeAdvertiser!!.stopAdvertising(mAdvertiseCallback)

    }

**Comment by frcc00** [comment]
does ios and android both have this problem?
i will check that asap.

**Comment by frcc00** [comment]
can you send a pr, please

**Comment by rebeccalee-ysd** [comment]
Hi, how is your day?


Sorry for replying late. I have forked your peripheral library and updated
with below link, you can have a look.

Worked on both iOS and android device.

Android: i have edited turn on peripheral to fix not work on old android
device. Also fixed read and write Ble msg method to fix the getService()
null issue.

Both write and read override method on IOS and Android is better to call a
response when received msg, also only need to mark the characteristic
setting when peripheral, characteristic for peripheral need to use
the peripheral one, not the connect device one.


https://github.com/rebeccalee-ysd/frccblue


If you have any questions, please feel free to contact my private email:
rebecca_wan1228@yahoo.com.hk


Thanks.

Regards

frcc00 <notifications@github.com> 於 2020年9月4日 週五 上午11:31寫道：
